### ISSUE TITLE
Where did you get the set of SURFSHARK_COUNTRY and SURFSHARK_CITY?

### ISSUE THREAD

**Issue by fabiohbarbosa** [ilteoood/docker-surfshark#10]
Sorry to make a question from here, but I didn't figure out another place to do that.
Where did you guys get the list of countries and cities code?

Thank you.

**Comment by ilteoood** [comment]
On [manual setup](https://my.surfshark.com/vpn/manual-setup/main) page, you'll find all the servers available right now.
In that page, you'll find the address of the server: [SURFSHARK_COUNTRY].[SURFSHARK_CITY].prod.surfshark.com

That's how we do it ;)
