### ISSUE TITLE
SOCKS5 Not working

### ISSUE THREAD

**Issue by Osama-Net** [ilteoood/docker-surfshark#100]
Hi, 

I have set ENABLE_SOCKS_SERVER=true and tested but it didn't work. i have also scanned it using nmap but it says the port is filtered (port 1080). actually both ports=1080 & 9091 are showing as filtered. but other ports on my docker server are showing as Open. 

I have checked the local firewalls on the container but it didn't have any rules. 

PORT     STATE    SERVICE
1080/tcp filtered socks

PORT     STATE    SERVICE
9091/tcp filtered xmltec-xmlmail

I noticed that the interface name in the sockd.conf file is different from the actual interface name:

`/vpn # cat /etc/sockd.conf
logoutput: stdout

internal: **eth0** port = 1080
external: tun0`

------------
`139: **eth0@if140**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:1d:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.29.0.2/16 brd 172.29.255.255 scope global eth0
       valid_lft forever preferred_lft forever`

I tried to change the interface name in the sockd.conf file but that borked the container and i had to redeploy it.

Any ideas?

**Comment by Osama-Net** [comment]
I found the issue. The "LAN_NETWORK=" variable was misconfigured.

Tested on qbittorrent and working fine now. 

Is there a way to allow connections from Any source? i tried 0.0.0.0/0 but it didn't work.

Thanks

**Comment by thefunkygibbon** [comment]
did you sort it? i'm wanting to know the same

**Comment by ilteoood** [comment]
I think that in order to achieve it, we should whitelist different IPs

**Comment by thefunkygibbon** [comment]
hmmm ok weird, if i leave the lan nets env variable blank it starts up ok, but i can't use the socks proxy,  but  if put my lan subnet in there 192.168.0.0/24 it doesnt start at all.

**Comment by thefunkygibbon** [comment]
ok scratch that, i just put it in again and restarted and its ok now ... very odd.
