### ISSUE TITLE
Not working with rpi

### ISSUE THREAD

**Issue by 2k20A** [ilteoood/docker-surfshark#11]
Hi,

The alpine docker container doesn't work on my raspberry pi 3+. Is it possible to build a docker compatible with this architecture ?

Thanks

**Comment by jmiller148** [comment]
You could do this yourself as it is not too hard if you are familiar with your OS and command line use.  My first time looking at and building a docker image was this one.  It works for me, but I wanted to try to build it myself.   It depends on your OS.   What OS are you running.

I don't want to take the owners space here, so we might want to move this discussion if you decide to try it and want some help.

**Comment by ilteoood** [comment]
IMO this is strange.
All my images are multi-arch and support both armv7, armv6 and arm64.
I use it without problems on my RPi 4, 8GB

**Comment by 2k20A** [comment]
Hi,
 
Thanks for the answers.

I'm running raspbian buster lite and omv 5 on a raspberry pi 3b+. Don't know where is the "bug".


The surfshark container works fine : healthy and the vpn route is establish

Alpine container is running but alpine log  
standard_init_linux.go:211: exec user process caused "exec format error"

Transmission container is running and transmission log
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2020-10-30 11:58:31.465] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)
[2020-10-30 11:58:31.475] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956)
[2020-10-30 11:58:31.475] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)
[2020-10-30 11:58:31.475] DHT Generating new id (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:389)
[2020-10-30 11:58:31.475] Using settings from "/config" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646)
[2020-10-30 11:58:31.475] Saved "/config/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
[2020-10-30 11:58:31.475] Watching "/watch" for new .torrent files (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:698)
[2020-10-30 11:58:31.475] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/natpmp.c:73)
[2020-10-30 11:58:31.475] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/natpmp.c:73)
[2020-10-30 11:58:39.473] Port Forwarding State changed from "Not forwarded" to "Starting" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:106)
[2020-10-30 11:59:30.473] DHT Attempting bootstrap from dht.transmissionbt.com (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:299)
[2020-10-30 12:00:39.473] Port Forwarding State changed from "Starting" to "???" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:106)

**Comment by ilteoood** [comment]
Can you paste the log of surfshark container? The transmission one isn't necessary

**Comment by 2k20A** [comment]
here it is

rch
Filter...
Lines
100
Actions  
      
  inflating: ovpn_configs/us-dal.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-dal.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-hou.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-hou.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-dtw.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-dtw.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-chi.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-chi.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-las.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-las.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-slc.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-slc.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-ltm.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-ltm.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/107.175.104.84_tcp.ovpn  


  inflating: ovpn_configs/107.175.104.84_udp.ovpn  


  inflating: ovpn_configs/199.229.250.163_tcp.ovpn  


  inflating: ovpn_configs/199.229.250.163_udp.ovpn  


  inflating: ovpn_configs/us-clt.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-clt.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/23.105.163.94_tcp.ovpn  


  inflating: ovpn_configs/23.105.163.94_udp.ovpn  


  inflating: ovpn_configs/us-stl.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-stl.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-bos.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-bos.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/107.181.166.39_tcp.ovpn  


  inflating: ovpn_configs/107.181.166.39_udp.ovpn  


  inflating: ovpn_configs/us-lax.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-lax.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-kan.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-kan.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc-st005.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc-st005.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc-st004.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc-st004.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_udp.ovpn  


  inflating: ovpn_configs/vn-hcm.prod.surfshark.com_tcp.ovpn  


  inflating: ovpn_configs/vn-hcm.prod.surfshark.com_udp.ovpn  


Chose: it-mil.prod.surfshark.com_udp.ovpn


Error: any valid prefix is expected rather than "".


Adding ip route add  via 172.20.0.1 dev eth0 for attached container web ui access


Do not forget to expose the ports for attached container we ui access


Fri Oct 30 10:58:28 2020 WARNING: file 'vpn-auth.txt' is group or others accessible


Fri Oct 30 10:58:28 2020 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020


Fri Oct 30 10:58:28 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10


Fri Oct 30 10:58:28 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit


Fri Oct 30 10:58:28 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication


Fri Oct 30 10:58:28 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication


Fri Oct 30 10:58:28 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.54.155:1194


Fri Oct 30 10:58:28 2020 Socket Buffers: R=[180224->180224] S=[180224->180224]


Fri Oct 30 10:58:28 2020 UDP link local: (not bound)


Fri Oct 30 10:58:28 2020 UDP link remote: [AF_INET]212.102.54.155:1194


Fri Oct 30 10:58:28 2020 TLS: Initial packet from [AF_INET]212.102.54.155:1194, sid=a8b3ce00 114a8107


Fri Oct 30 10:58:28 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this


Fri Oct 30 10:58:28 2020 VERIFY OK: depth=2, C=VG, O=Surfshark, CN=Surfshark Root CA


Fri Oct 30 10:58:28 2020 VERIFY OK: depth=1, C=VG, O=Surfshark, CN=Surfshark Intermediate CA


Fri Oct 30 10:58:28 2020 VERIFY KU OK


Fri Oct 30 10:58:28 2020 Validating certificate extended key usage


Fri Oct 30 10:58:28 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication


Fri Oct 30 10:58:28 2020 VERIFY EKU OK


Fri Oct 30 10:58:28 2020 VERIFY OK: depth=0, CN=it-mil-v046.prod.surfshark.com


Fri Oct 30 10:58:28 2020 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1633', remote='link-mtu 1581'


Fri Oct 30 10:58:28 2020 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'


Fri Oct 30 10:58:28 2020 WARNING: 'auth' is used inconsistently, local='auth SHA512', remote='auth [null-digest]'


Fri Oct 30 10:58:28 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA


Fri Oct 30 10:58:28 2020 [it-mil-v046.prod.surfshark.com] Peer Connection Initiated with [AF_INET]212.102.54.155:1194


Fri Oct 30 10:58:30 2020 SENT CONTROL [it-mil-v046.prod.surfshark.com]: 'PUSH_REQUEST' (status=1)


Fri Oct 30 10:58:30 2020 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 162.252.172.57,dhcp-option DNS 149.154.159.92,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,block-outside-dns,route-gateway 10.8.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.19 255.255.255.0,peer-id 18,cipher AES-256-GCM'


Fri Oct 30 10:58:30 2020 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:7: block-outside-dns (2.4.9)


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: timers and/or timeouts modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: explicit notify parm(s) modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified


Fri Oct 30 10:58:30 2020 Socket Buffers: R=[180224->360448] S=[180224->360448]


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: --ifconfig/up options modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: route options modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: route-related options modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: peer-id set


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: adjusting link_mtu to 1656


Fri Oct 30 10:58:30 2020 OPTIONS IMPORT: data channel crypto options modified


Fri Oct 30 10:58:30 2020 Data Channel: using negotiated cipher 'AES-256-GCM'


Fri Oct 30 10:58:30 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Fri Oct 30 10:58:30 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Fri Oct 30 10:58:30 2020 ROUTE_GATEWAY 172.20.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:14:00:02


Fri Oct 30 10:58:30 2020 TUN/TAP device tun0 opened


Fri Oct 30 10:58:30 2020 TUN/TAP TX queue length set to 100


Fri Oct 30 10:58:30 2020 /sbin/ip link set dev tun0 up mtu 1500


Fri Oct 30 10:58:30 2020 /sbin/ip addr add dev tun0 10.8.8.19/24 broadcast 10.8.8.255


Fri Oct 30 10:58:30 2020 /sbin/ip route add 212.102.54.155/32 via 172.20.0.1


Fri Oct 30 10:58:30 2020 /sbin/ip route add 0.0.0.0/1 via 10.8.8.1


Fri Oct 30 10:58:30 2020 /sbin/ip route add 128.0.0.0/1 via 10.8.8.1


Fri Oct 30 10:58:30 2020 Initialization Sequence Completed

**Comment by ilteoood** [comment]
Here there isn't any exec format error...btw, the VPN is up and running, so isn't true that isn't working on rpi :)

**Comment by 2k20A** [comment]
yup, I agree, wrong title :)

But the exec format error is in the alpine container log

**Comment by jmiller148** [comment]
I failed to tell you that I had that same issue for the "service test".  I had simply removed it from my compose file.  After testing and verifying it was still working properly I assumed it was not needed.

I'm not familiar with alpine but I see the creator of that container is calling out a version of Alpine (FROM alpine:3.10) where you are using the latest.

**Comment by ilteoood** [comment]
The service test is just an example to show that the VPN is up and running (infact is used just to see the new IP).
It is not needed to execute docker surfshark.

**Comment by ilteoood** [comment]
So, @jmiller148, the fork that you made isn't necessary: this image already support arm64

**Comment by jmiller148** [comment]
Yes you are correct.  I rebuilt the  "byrnedo/alpine-curl" container using "FROM alpine:latest" and it worked as expected.  Funny thing if you remember I said I had to seperate my compose file into single containers.  With the "service_test" it all loaded as one compose file.

**Comment by 2k20A** [comment]
hmm, maybe it's the version of alpine....

Anyway, when i remove the alpine service, it works but I can't acces to the webui of the transmission container. So it's quite complicated to actually use the transmission container...

**Comment by jmiller148** [comment]
To the OP if you remove service test you can confirm your IP is that of the VPN.  Unlike what I was used to you will use /bin/ash to shell into the container.  Then you can use "curl ifconfig.me" to see what the current IP is.

**Comment by jmiller148** [comment]
I am able to connect to Transmission after removing service test.   Also make sure your LAN_NETWORK is correct for your network.  You may have 192.168.1.0/24 instead as that is common also.

**Comment by 2k20A** [comment]
Indeed, I have the ip of the container but impossible to acces to the port from my lan nor the wan.
192.168.0.XX:9091 doesn't work
111.222.333.52:9091 doesn't work (vpn ip)

My surshark container open port 9091 for transmission. How can I acces the webui of this port ?

**Comment by jmiller148** [comment]
> So, @jmiller148, the fork that you made isn't necessary: this image already support arm64

I removed the arm64 repo.  I do not see a reason for it.  😁

**Comment by 2k20A** [comment]
My raspberry pi is 192.168.0.33.
I put in the lan network of surfshark container 192.168.0.0/24
The ip adress of the surfshark network created in portainer is 172.22.0.2 (and gateway 172.22.0.1)
The vpn ip is 12.13.14.15

I feel that i'm almost done but I can't acces to the webui. Could you hep me ? What do I need to change in this configs to make it work ?

**Comment by jmiller148** [comment]
Are you on ethernet or wireless?

**Comment by 2k20A** [comment]
ethernet. the rasp is directly link to my provider modem

**Comment by jmiller148** [comment]
Well I have no idea then.  I even tested it on wifi and I can still access transmission.  Are you using a proxy by chance?

**Comment by 2k20A** [comment]
no proxy. 

When you want to acces transmission, you do it by entering the vpn ip :9091 ? or something else ?

**Comment by jmiller148** [comment]
No your pi ip + port.  Example 192.168.0.160:9091.  160 is the ip of my pi.

**Comment by jmiller148** [comment]
@ilteoood I realized why my compose file would not load as a complete file.  I DID actually change something  instead of service:surfshark I had container:surfshark.

**Comment by 2k20A** [comment]
I found the "errors".

First, the lan network of surfshark container was empty. So I put 192.168.0.0/24.
Then, the network mode of the transmission container was on bridge. So I turned it to container : surfshark
And the path of the qbittorrent config files was by default, so I changed them manually

And, magic, IT WORKED !!!!!!!!!!!!!!!!!!!!!!!

Thanks you all guys for helped me found the solution.

Could it be possible to add those variables in the docker compose (network lan, PUID and PGUId for qbittorrent, qbittorrent password...). I tried but with no success

**Comment by jmiller148** [comment]
You must have made changes to the original compose file found here.  I did the same at first.  If you use the compose file here and just add your surfshark user/pass and remove the service_test it would be fine.  At least you worked your way through it.
