### ISSUE TITLE
Doesnt work with my setup

### ISSUE THREAD

**Issue by ghost** [ilteoood/docker-surfshark#14]
Hi, I am trying to use this to access tvheadend and jellyfin so I can VPN IPTV and it doesnt work. Sometimes it connects to dockers but traffic doesnt go through VPN even  when it says surfshark is healthy 

Codes used:

`sudo docker run -it 
--cap-add=NET_ADMIN 
--device /dev/net/tun 
--name=surfshark 
-e SURF-SHARK_USER=MYUSERNAME
-e SURFSHARK_PASSWORD=MYPASSWORD 
ilteoood/docker-surfshark`

I have also added ports in surfshark (by accessing through portainer) and added ports forwarding 
192.168.1.255:8096 - 8096 for jellyfin
192.168.1.255:9981-9982 - 9981-9982 tvheadend
and added -e LAN_NETWORK=192.168.1.255/24

code for tvheadend

`sudo docker run -d \
  --name=tvheadend \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  --net=container:surfshark \
  -v /Docker/tvheadend:/config \
  -v /Downloads/recordings:/recordings \
  --restart unless-stopped \
  linuxserver/tvheadend
`

**Comment by vascobraga41** [comment]
I see at least 2 problems there, the port should be directly "9981:9981" and so on, you address only the port not the full IP, and in lan network you have to put your network  like "192.168.1.0/24" not the IP address of your device.

**Comment by ilteoood** [comment]
The suggestions of @vascobraga41 are correct. Tysm!

I suggest also to spin up this stack using a compose file. It should be easier for you to manage

**Comment by ghost** [comment]
> I see at least 2 problems there, the port should be directly "9981:9981" and so on, you address only the port not the full IP, and in lan network you have to put your network like "192.168.1.0/24" not the IP address of your device.

That seems to make it work, what would be the easiest way to check if the traffic is going through the VPN ?

**Comment by ilteoood** [comment]
Connect to the tvheadend container and run curl -L 'https://ipinfo.io'. You must see a different IP to the one you have for the rest of the network

**Comment by ghost** [comment]
> Connect to the tvheadend container and run curl -L 'https://ipinfo.io'. You must see a different IP to the one you have for the rest of the network

it keeps doing this 

Mon Dec  7 18:56:39 2020 Attempting to establish TCP connection with [AF_INET]206.189.119.82:1443 [nonblock]
,Mon Dec  7 18:58:39 2020 TCP: connect to [AF_INET]206.189.119.82:1443 failed: Operation timed out
,Mon Dec  7 19:27:14 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit
,Mon Dec  7 19:27:14 2020 NOTE: --fast-io is disabled since we are not using UDP
,Mon Dec  7 19:27:14 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]206.189.119.82:1443
,Mon Dec  7 19:27:14 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
,Mon Dec  7 19:27:14 2020 Attempting to establish TCP connection with [AF_INET]206.189.119.82:1443 [nonblock]
,Mon Dec  7 19:29:14 2020 TCP: connect to [AF_INET]206.189.119.82:1443 failed: Operation timed out
,Mon Dec  7 19:29:14 2020 SIGUSR1[connection failed(soft),init_instance] received, process restarting
,Mon Dec  7 19:29:14 2020 Restart pause, 300 second(s)

**Comment by ilteoood** [comment]
The connection is timed out in this case. Try to spin up the container with the --dns 8.8.8.8 option

**Comment by ghost** [comment]
Hi Guys it looks like it works now :) I have tested IPTV during premier league games and its fine :D thanks for your help
