### ISSUE TITLE
Wireguard support via env variable?

### ISSUE THREAD

**Issue by zilexa** [ilteoood/docker-surfshark#15]
Surfshark support Wireguard. Are you considering to add support for it?

**Comment by ilteoood** [comment]
I'm really thinking about it, but instead of env variable I would like to create a specific tag for the image, in order to keep it as smallest as possible

**Comment by zilexa** [comment]
Makes even more sense if you want to win the prize for the most lightweight and fast image. You got my vote :) 

BTW on their website they actually do not mention Wireguard support for Linux :( 
I just cancelled my NordVPN subscription as they still do not have port forwarding support and your image makes swithing to SurfShark an easy choice (I currently use [this image](https://github.com/Joentje/nordvpn-proxy)). The great thing about that image: it automatically selects the best Nordvpn server and checks if that server is still healthy, otherwise it switches to a different one. This could be a NordVPN feature, probably not something you can built in as a client. )

**Comment by zilexa** [comment]
Edit: I believe SurfShark has something similar: "Optimal Location", when you use that, it will autoselect the best server. Perhaps a daily reconnect with their server (if they provide the ability) would be an interesting feature.

**Comment by ilteoood** [comment]
I've implemented the automatic connection to the suggested country in this branch: https://github.com/ilteoood/docker-surfshark/tree/connection_suggest.
Can you build it and test if something like this can be useful?
With that implementation, SURFSHARK_USER and SURFSHARK_PASSWORD are the credentials used to log-in in the Surfshark's private area.
Let me know,

Matteo

**Comment by zilexa** [comment]
I dont have a SurfShark (paid) account yet. I was just about to get it, creditcard ready, when I found this huge blog article on their site:

At the very end they say they do not support port forwarding! Unfortunately, that means no SurfShark for me :( probably just going for PIA. Sorry. 

https://surfshark.com/blog/vpn-port-forwarding
