### ISSUE TITLE
[Question] Does this container support kill switch.

### ISSUE THREAD

**Issue by blmhemu** [ilteoood/docker-surfshark#16]
When the connectivity is lost does it stop traffic flow ?

**Comment by ilteoood** [comment]
When the connection close, the container will terminate so the other containers attached to it will stop to access the network.
You emulate it with wrong credentials

**Comment by HuiiBuh** [comment]
I am not sure if I am right, but it does not look like you implemented a kill switch. You did not modify the ip tables, to prevent the leaking of your ip address.

How did you achieve the kill switch if you did not modify the ip tables?
