### ISSUE TITLE
cannot connect to trasmission GUI except for from localhost

### ISSUE THREAD

**Issue by KCS-Mack** [ilteoood/docker-surfshark#18]
I am unable to connect to the Transmission GUI unless I do an ssh tunnel or from the local computer.  For example, my local ip is : 10.0.5.6, when I try to connect on my local network to 10.0.5.6:9091 I cannot connect(unless I do ssh tunnel), however I can connect from the server itself using localhost:9091.  Any idea how to bridge the port to my local ip address so 10.0.5.6 works?  Thanks!

**Comment by ilteoood** [comment]
Did you tried the compose file provided?
You must also configure the lan network parameter

**Comment by KCS-Mack** [comment]
hey! I figured it out man

Thank you for the message.  You have to map the local ip to the port number
in the config as well
I'm not sure if you want to add that to your github or not.

    ports:
      - "10.0.1.202:9091:9091"

**Comment by ilteoood** [comment]
That configuration depends on your network, for the other is useless.
I'm happy that you fixed it ☺

**Comment by KCS-Mack** [comment]
Matteo,

Hmm, still not working the way I want it to.  I cannot connect to it from
my local address:port number when on vpn.  Is there a way to give the
surfshark container a mac address and dhcp address?

Thanks,

Mack

**Comment by ilteoood** [comment]
To do that you must use the LAN_NETWORK environment variable.

**Comment by KCS-Mack** [comment]
I did that but it still doesn’t work.

For example I tried

192.168.1.5
And

192.168.1.0/24

As the lan_network environment variable but no success.

Also trying to add it to a macvlan network but not working either

**Comment by KCS-Mack** [comment]
Other containers with the -p variable work fine (portainer, traefic, etc)

**Comment by ilteoood** [comment]
Are you using docker compose or the docker run command?
Can you attach here the full commands that you use?

**Comment by KCS-Mack** [comment]
Hey man! figured it out.  an easier way to do it(rather than making a
reverse proxy) was to just cut out a few ip address on my local network and
give it out in the docker-compose file.


Basically created the network like this:

networks:
  internalnetwork:
    driver: bridge
    name: internalnetwork
    ipam:
      driver: default
      config:
          - subnet: 10.0.4.128/25

then in the container I had this

    environment:
      - LOCAL_NETWORK=10.4.0.0/22
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
    networks:
#     - reverse-proxy-network
     - internalnetwork

then my local network ip range is

10.0.4.0/25

Works pretty well!


Thanks for your help.


Mack
