### ISSUE TITLE
Unable to specify multiple subnets for LAN_NETWORK

### ISSUE THREAD

**Issue by iBeech** [ilteoood/docker-surfshark#19]
Hey team,

I have multiple VLANs on my network. My docker containers run on the 192.168.3.0/24 subnet, and need to talk to each other, and I access the web interfaces from 192.168.2.0/24.

Right now, I can either let the containers talk to eachother and not be able to access any of the containers from my main network  OR containers can't talk to each other, but I can connect from my main network.

Ideally, the LAN_NETWORK variable can take multiple subnets to allow access to them all e.g.

     - LAN_NETWORK=192.168.2.0/24,192.168.3.0/24

Think this could be possible?

**Comment by ilteoood** [comment]
I think that can be possible.
Do you want to make a PR?

**Comment by iBeech** [comment]
@ilteoood PR Open https://github.com/ilteoood/docker-surfshark/pull/20

I've not written bash before, so please forgive me if there are any mistakes.
