### ISSUE TITLE
Wrongly named OpenVPN configuration files

### ISSUE THREAD

**Issue by lucanello** [ilteoood/docker-surfshark#2]
Configuration files retrieved via https://api.surfshark.com/v1/server/configurations are partly named with IP-addresses and only a few of the locations are named with country codes in front.

It's not really a bug that this project is responsible for but still important because it affects the possibilities. Currently only a few connections can be established because of wrong the wrong naming.

Example for correctly named configuration file: `us-dal.prod.surfshark.com_tcp.ovpn`
Example for wrongly named configuration file: `185.108.106.19_tcp.ovpn`

**Comment by lucanello** [comment]
Update: I messaged the support team and they will notify me as soon as there is a fix. They are working on it. But the support contact also said that only a few people are using this API, so let's hope they care.

**Comment by ilteoood** [comment]
Hi Luca,
I'm happy that you already wrote to the Surfshark support.
I admit: when I started this project there wasn't any IP address in that zip, infact the script that choose the correct .ovpn file is the same that I used for my router.

I'll keep this open, just as reminder.

Thank you for the help,
Matteo

**Comment by lucanello** [comment]
It seems like they fixed that and named everything correctly, awesome! I would still keep this merged PR in master because it has no disadvantages.

**Comment by ilteoood** [comment]
Looks great.
I think that I'll implement the support for the region!

**Comment by lucanello** [comment]
> Looks great.
> I think that I'll implement the support for the region!

What exactly do you mean by region? Like `it` for italy? Because this can still be achieved by setting SURFSHARK_COUNTRY=it
