### ISSUE TITLE
unable to resolve api.surfshark.com

### ISSUE THREAD

**Issue by 2k20A** [ilteoood/docker-surfshark#22]
Hi,
Container error since this morning. Any clue to solve this ?

wget: unable to resolve host address 'api.surfshark.com'

chive:  ovpn_configs.zip

  End-of-central-directory signature not found.  Either this file is not

  a zipfile, or it constitutes one disk of a multi-part archive.  In the

  latter case the central directory and zipfile comment will be found on

  the last disk(s) of this archive.

unzip:  cannot find zipfile directory in one of ovpn_configs.zip or

        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.

./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory

ls: cannot access 'it*': No such file or directory

Chose:

Adding ip route add 192.168.0.0/24 via 172.26.0.1 dev eth0 for attached container web ui access

Do not forget to expose the ports for attached container we ui access

Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.0)

Use --help for more information.

--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations

Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.

**Comment by ilteoood** [comment]
Hi, did you updated the container? Which version of the image are you using?

**Comment by 2k20A** [comment]
I use 

ilteoood/docker-surfshark:latest
--

after a sudo docker pull ilteoood/docker-surfshark:latest
it said image is up to date


How do u update a container in portainer ?

**Comment by ilteoood** [comment]
Can u share the sha the image that you're using? this doesn't give too much informations.

**Comment by 2k20A** [comment]
sha256:014f5be0e287467e543aad6d7f4fcccbda814cca73e8a964622efcb1b444242f

**Comment by ilteoood** [comment]
I suggest you to delete your current container, remove the image, pull the latest one and re-deploy.
If continue to not work, please provide you compose file.

**Comment by 2k20A** [comment]
I restored omv and portainer (3 days ago). 
Maybe it's due to the portainer update 2.0.1 ? The rollback worked so I will let it that way.

**Comment by mr-ransel** [comment]
Hmmm, I'm running into this same issue with `sha256:95885c2311b193a9b8db13273205cbb8a58f8d823a0e904dbb95dd132a6eb01d`, from 5 days ago (running on a raspberry pi 4), with the vanilla example docker-compose yaml (and my creds obviously).

**Comment by mr-ransel** [comment]
Ahh, probably the issue here:

```
$ sudo docker run -i -t --rm --entrypoint="/bin/sh" byrnedo/alpine-curl
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

(I'll break this into a separate issue)
