### ISSUE TITLE
Image doesn't appear to actually be multi-architecture

### ISSUE THREAD

**Issue by mr-ransel** [ilteoood/docker-surfshark#24]
👋 In the readme you reference that this is multi-arch image, and while you have a github workflow set up to build mullti-arch images, the tags are misleading because they're all based on top of the [byrnedo/alpine-curl](https://hub.docker.com/r/byrnedo/alpine-curl/tags?page=1&ordering=last_updated) image, which is only available for the `linux/amd64` architecture, introducing problems on other architectures.

The easiest fix is to just use the normal alpine image and throw curl in on top of it.

**Comment by mr-ransel** [comment]
For example: https://github.com/ilteoood/docker-surfshark/issues/22#issuecomment-787103969

**Comment by ilteoood** [comment]
byrnedo/alpine-curl is just an example service spinned up as tests, in order to see that your ip is changing.
You don't have to spin up it in your setup.
The image is multi-arch, as shown in the docker registry.

**Comment by mr-ransel** [comment]
🤦 Yeah, fair point. I guess I was grasping at straws to explain why I'm running into this https://github.com/ilteoood/docker-surfshark/issues/22#issuecomment-787103027 

```
$ sudo docker run -i -t --rm --entrypoint="/bin/sh" ilteoood/docker-surfshark
/vpn # wget -O ovpn_configs.zip https://api.surfshark.com/v1/server/configurations
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.
wget: unable to resolve host address 'api.surfshark.com'
/vpn # nslookup api.surfshark.com
nslookup: clock_gettime(MONOTONIC) failed
```

Closer inspection shows that it's a problem with `alpine:latest` as well, so I'll keep running that down separately

**Comment by mr-ransel** [comment]
Appears to be specific to `alpine:3.13.0` 
```
$ sudo docker run -i -t --rm --entrypoint="/bin/sh" alpine:3.12.4
/ # nslookup api.surfshark.com
Server:		192.168.29.1
Address:	192.168.29.1:53

Non-authoritative answer:
Name:	api.surfshark.com
Address: 104.20.107.83
Name:	api.surfshark.com
Address: 172.67.17.41
Name:	api.surfshark.com
Address: 104.20.106.83

Non-authoritative answer:
Name:	api.surfshark.com
Address: 2606:4700:10::6814:6a53
Name:	api.surfshark.com
Address: 2606:4700:10::6814:6b53
Name:	api.surfshark.com
Address: 2606:4700:10::ac43:1129

/ # exit
$ sudo docker run -i -t --rm --entrypoint="/bin/sh" alpine:3.13.0
/ # nslookup api.surfshark.com
nslookup: clock_gettime(MONOTONIC) failed
```

Sorry, not your problem @ilteoood, but FYI if anyone comes along with this issue, just build off of `alpine:3.12.4` instead

**Comment by ilteoood** [comment]
Did you tried specifying the dns in the compose file?

**Comment by mr-ransel** [comment]
Yeah I dug a lot deeper on this and tracked it back to a specific update of the alpine image here: https://github.com/dperson/openvpn-client/issues/365#issuecomment-787133320

essentially alpine made an update that raspbian stable doesn't support yet. By manually digging up the debian dpkg I was able to get things mostly working, now I'm just debugging some (probably) unrelated openvpn/surfshark tls errors: 
```
2021-02-28 02:24:44 Restart pause, 300 second(s)
2021-02-28 02:29:44 WARNING: --ping should normally be used with --ping-restart or --ping-exit
2021-02-28 02:29:44 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2021-02-28 02:29:44 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
2021-02-28 02:29:44 TCP/UDP: Preserving recently used remote address: [AF_INET]165.232.53.25:1194
2021-02-28 02:29:44 Socket Buffers: R=[180224->180224] S=[180224->180224]
2021-02-28 02:29:44 UDP link local: (not bound)
2021-02-28 02:29:44 UDP link remote: [AF_INET]165.232.53.25:1194
2021-02-28 02:30:44 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2021-02-28 02:30:44 TLS Error: TLS handshake failed
2021-02-28 02:30:44 SIGUSR1[soft,tls-error] received, process restarting
```
