### ISSUE TITLE
troubleshooting surfshark issues

### ISSUE THREAD

**Issue by RookieKiwi** [ilteoood/docker-surfshark#25]
Hey Team,

First of all thanks for your hard work, I am a bit of a rookie so please bare with me on this, i am trying to create a netflix proxy that connects to surfshark, i am having issues with the other containers getting no internet access, i am unable to troubleshoot the connection as for some reason when i try to attach to the surfshark container it just hangs on me :/, below is my docker compose to give you an idea of what im trying to do, the other containers appear to be unable to access the internet.

version: '2'

services:
  surfshark:
   image: ilteoood/docker-surfshark
   container_name: surfshark
   environment:
       - SURFSHARK_USER=X
       - SURFSHARK_PASSWORD=Y
       - SURFSHARK_COUNTRY=au
       - SURFSHARK_CITY=syd
       - CONNECTION_TYPE=udp
       - LAN_NETWORK=192.168.0.0/24      #Optional - Used to access attached containers web ui
   cap_add:
       - NET_ADMIN
   devices:
       - /dev/net/tun
   ports:
       - 8080:8080
       - 80:80
       - 53:53
       - 5353:5353
       - 443:443
   restart: unless-stopped
   dns:
       - 1.1.1.1

  dnsmasq-service:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    privileged: true
    network_mode: service:surfshark
    depends_on:
      - surfshark
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: always

  dnsmasq-bogus-service:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq-bogus
    privileged: true
    network_mode: service:surfshark
    depends_on:
      - surfshark
    cap_add:
      - NET_ADMIN
    command: --port=5353 --log-facility=- -A /#/${EXTIP} -A /#/${EXTIP6}
    restart: always

  caddy-service:
    image: abiosoft/caddy:latest
    container_name: caddy
    privileged: true
    network_mode: service:surfshark
    cap_add:
      - NET_ADMIN
    depends_on:
      - surfshark
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./wwwroot:/srv
    restart: always

  sniproxy-service:
    image: ab77/sniproxy:latest
    container_name: sniproxy
    build:
      context: docker-sniproxy
    privileged: true
    network_mode: service:surfshark
    cap_add:
      - NET_ADMIN
    depends_on:
      - surfshark
    volumes:
      - ./docker-sniproxy/sniproxy.conf:/etc/sniproxy.conf
    restart: always

I am basically trying to merge https://github.com/ab77/netflix-proxy and this together to create a setup that VPNs the proxy

**Comment by ilteoood** [comment]
What team? Is just me 😁😁
BTW, why are you trying to create a smart dns proxy, that surfshark already provide with your subscription? I suggest you to adopt it.

**Comment by RookieKiwi** [comment]
I want to proxy things other then Netflix from other countries
