### ISSUE TITLE
directly use an ovpn file

### ISSUE THREAD

**Issue by 2k20A** [ilteoood/docker-surfshark#26]
Hi. The container works well but each time it reboots, the ip change. I have a static ovpn file for surfshark and I would like to know if it's possible to directly use it in the container instead of automatically have one by connecting to surfshark pro...

**Comment by ilteoood** [comment]
It is not possible, because the ovpn files are dowloaded at startup.
You can try to filter and retrieve it using the city and country properties, but it is still downloaded from surfshark.
