### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by 2k20A** [ilteoood/docker-surfshark#28]
Hi, 
I have an issue with the docker

Adding ip route add 192.168.0.0/24 via 172.17.0.1 dev eth0 for attached container web ui access
Do not forget to expose the ports for attached container we ui access
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2)
Use --help for more information.
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.
wget: unable to resolve host address 'api.surfshark.com'
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.
chive:  ovpn_configs.zip
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory
ls: cannot access 'it*': No such file or directory

**Comment by ilteoood** [comment]
Can you give me a little bit of detail, please?

For example, image version, dockerfile sample...

**Comment by 2k20A** [comment]
Hey,
config : rapsberry pi 4 4go + OMV + docker + portainer 2.1.1
image version : the last one up to date, I just create the docker
image ID : sha256:e5c377953723421816cf2c928efebbf1e37deaa5f2eafd5a2293f55e14660a84

**Comment by ilteoood** [comment]
Can you also share the way in which you configure it? (e.g. docker run command, docker-compose file...)

**Comment by 2k20A** [comment]
I let him all by default. Just entered my vpn username and password.

BUT I FIXED IT

the bug is due to a wrong version of libseccomp. Once manually updated, it worked just fine.

https://docs.linuxserver.io/faq#libseccomp
