### ISSUE TITLE
error with given test config

### ISSUE THREAD

**Issue by pakyrs** [ilteoood/docker-surfshark#29]
Thanks for the awesome image. But I can't get it to work maybe I am being a bit thick!

I am using your test docker compose yaml with my home network range  the rest is pretty much identical:

`services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USE=**********
            - SURFSHARK_PASSWORD=********
            - SURFSHARK_COUNTRY=gb
            - SURFSHARK_CITY=lon
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=192.168.3.198/24
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 9091:9091 #we open here the port for transmission, as this container will be the access point for the others
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        #ports:
            #- 9091:9091 needed to access transmission's GUI
        network_mode: service:surfshark
        restart: unless-stopped`

This is what I end up getting. I am running on rpi4 and had transmission working OK before, without VPN. 

`
Starting alpine ... 
Starting transmission ... 
[1A[2K
Starting transmission ... [31merror[0m
[1B
ERROR: for transmission  Cannot start service transmission: Container 26f732af41a8b3d9bb32c8c00cd56607885fa6ba3e598bd55353f64efbeae12b is restarting, wait until the container is running
[2A[2K
Starting alpine       ... [31merror[0m
[2B
ERROR: for alpine  Cannot start service service_test: Container 26f732af41a8b3d9bb32c8c00cd56607885fa6ba3e598bd55353f64efbeae12b is restarting, wait until the container is running

ERROR: for transmission  Cannot start service transmission: Container 26f732af41a8b3d9bb32c8c00cd56607885fa6ba3e598bd55353f64efbeae12b is restarting, wait until the container is running

ERROR: for service_test  Cannot start service service_test: Container 26f732af41a8b3d9bb32c8c00cd56607885fa6ba3e598bd55353f64efbeae12b is restarting, wait until the container is running
Encountered errors while bringing up the project.`

Looks like the surfshark container isn't ready or it keep restarting hence alpine and transmissions can't run I guess. 
`

Thanks for helping I am also new to github in general I hope its OK to post here. 

Best

Pasquale

**Comment by pakyrs** [comment]
This is the log from surfshark container:

`
wget: unable to resolve host address 'api.surfshark.com',
chive:  ovpn_configs.zip,
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations,
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.,
wget: unable to resolve host address 'api.surfshark.com',
chive:  ovpn_configs.zip,
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations,
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.,
wget: unable to resolve host address 'api.surfshark.com',
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
chive:  ovpn_configs.zip,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations,
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.,
wget: unable to resolve host address 'api.surfshark.com',
chive:  ovpn_configs.zip,
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations,
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.,
wget: unable to resolve host address 'api.surfshark.com',
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
chive:  ovpn_configs.zip,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
--2106-02-07 06:28:16--  https://api.surfshark.com/v1/server/configurations,
Resolving api.surfshark.com (api.surfshark.com)... failed: Try again.,
wget: unable to resolve host address 'api.surfshark.com',
chive:  ovpn_configs.zip,
  End-of-central-directory signature not found.  Either this file is not,
  a zipfile, or it constitutes one disk of a multi-part archive.  In the,
  latter case the central directory and zipfile comment will be found on,
  the last disk(s) of this archive.,
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or,
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.,
./startup.sh: cd: line 5: can't cd to ovpn_configs: No such file or directory,
ls: cannot access 'it*': No such file or directory,
Chose:,
Adding ip route add 192.168.3.0/24 via 172.19.0.1 dev eth0 for attached container web ui access,
Do not forget to expose the ports for attached container we ui access,
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2),
Use --help for more information.,
`

**Comment by ilteoood** [comment]
Hi,
It can't retrieve the zip containing the VPN configurations.

Can you post here how you boot the container, omitting username and password?

**Comment by pakyrs** [comment]
Hi Matteo, 

Thanks, see below my docker compose file:

---
version: "2"

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USE=****
            - SURFSHARK_PASSWORD=****
            - SURFSHARK_COUNTRY=it
            - SURFSHARK_CITY=mil
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=192.168.3.0/24
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 9091:9091 #we open here the port for transmission, as this container will be the access point for the others
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        #ports:
            #- 9091:9091 needed to access transmission's GUI
        network_mode: service:surfshark
        restart: unless-stopped`

`

**Comment by vascobraga41** [comment]
I had a similar problem and had to stay in older images for a while but solved it when read issue #28 . I just manually updated `libseccomp` in my Ubuntu 18.04 and it was solved.

**Comment by pakyrs** [comment]
thanks Vasco! is the libseccomp needing updates on my docker host (RaspberryPi) or any of the containers being spun from this git? Surfshark, Alpine, Transmission?

Sorry, I am just new to Docker overall.

Thanks

Pasquale

**Comment by vascobraga41** [comment]
I updated my docker host, so try it.

**Comment by pakyrs** [comment]
Thanks Vasco! It seems to work now.

If anyone needs this is what I run on the Pi4:

```
# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138

# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports
```
