### ISSUE TITLE
How to attach other container to VPN

### ISSUE THREAD

**Issue by FedeltaMedia** [ilteoood/docker-surfshark#3]
The documentation isn't very extensive. How to add a container to the VPN?
I see there is a command in the readme:
`sudo docker run -it --net=container:CONTAINER_NAME alpine /bin/sh`

But this command is unclear to me. Does `CONTAINER_NAME` need to contain the name of the VPN container or of the container you're trying to attach? Also what does '**alpine**' mean? There is only 1 image file in this github which is called '**ilteoood:docker-surfshark**', correct?

**Comment by ilteoood** [comment]
Hi, this is specified with the first part of the docunentation.
CONTAINER_NAME is the name of the container that you create using the docker-surfshark image.
Alpine is the image of the container that you want to attach to the VPN.

**Comment by ilteoood** [comment]
sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name CONTAINER_NAME -e SURFSHARK_USER=YOUR_SURFSHARK_USER -e SURFSHARK_PASSWORD=YOUR_SURFSHARK_PASSWORD ilteoood:docker-surfshark

**Comment by ilteoood** [comment]
With this command, you create a container named CONTAINER_NAME that is base on docker-surfshark (as described)

**Comment by ilteoood** [comment]
And with the other one you attach the container that you are creating to the VPN.
