### ISSUE TITLE
Unrecognized option or missing or extra parameter(s)

### ISSUE THREAD

**Issue by xavier7179** [ilteoood/docker-surfshark#30]
Everything worked out smoothly until today when the container restarted suddenly, and then in the logs I found:

`Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2)`

**Comment by ilteoood** [comment]
Which country are you using to connect?

**Comment by xavier7179** [comment]
Italy, same settings of the example

**Comment by ilteoood** [comment]
Is a duplicate of #29.

See the solution in that issue.

**Comment by abhilesh** [comment]
I'm having the same issue trying to run the container on an Ubuntu 20.04 VM running over Proxmox. 
Docker version: 20.10.9, Docker-compose version: 1.29.2

I am able to connect to the API to pull vpn files but then the container keeps restarting with the following line in the logs - 
```Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.2)```

I have already update libseccomp2 to version 2.5.2-2 and the error still persists.

What other steps can I take to prevent the container from constantly restarting?

**Comment by ilteoood** [comment]
Hi @abhilesh, which country did you choose for the connection?

**Comment by abhilesh** [comment]
Hi @ilteoood, I was connecting from the US. I figured out what the issue was. SurfShark updated their server addresses and the server address I was using to connect was no longer available in the list of locations, updating the location servers based on SurfSharks latest server list resolved the issue.
