### ISSUE TITLE
different .ovpn filenames style in ovpn_configs.zip

### ISSUE THREAD

**Issue by ilmarietto123** [ilteoood/docker-surfshark#31]
I found some .ovpn files have different filename style in the last ovpn_configs.zip downloaded from the container.
To connect to "it-mil.prod.surfshark.com_udp.ovpn", now named "37.120.201.19_udp.ovpn", putting SURFSHARK_COUNTRY=37.120.201.19_udp and SURFSHARK_CITY empty, worked for me.

`
Archive:  ovpn_configs.zip

  inflating: ovpn_configs/al-tia.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/al-tia.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ar-bua.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ar-bua.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/45.248.79.67_tcp.ovpn  

  inflating: ovpn_configs/45.248.79.67_udp.ovpn  

  inflating: ovpn_configs/au-per.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/au-per.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/au-mel.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/au-mel.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/au-syd.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/au-syd.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/au-bne.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/au-bne.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/at-vie.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/at-vie.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/az-bak.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/az-bak.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/be-bru.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/be-bru.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/be-anr.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/be-anr.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ba-sjj.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ba-sjj.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/br-sao.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/br-sao.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/bg-sof.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/bg-sof.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ca-tor-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ca-tor-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ca-tor.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ca-tor.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/172.98.82.245_tcp.ovpn  

  inflating: ovpn_configs/172.98.82.245_udp.ovpn  

  inflating: ovpn_configs/107.181.177.179_tcp.ovpn  

  inflating: ovpn_configs/107.181.177.179_udp.ovpn  

  inflating: ovpn_configs/cl-san.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/cl-san.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/co-bog.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/co-bog.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/cr-sjn.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/cr-sjn.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/hr-zag.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/hr-zag.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/cy-nic.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/cy-nic.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/193.9.112.179_tcp.ovpn  

  inflating: ovpn_configs/193.9.112.179_udp.ovpn  

  inflating: ovpn_configs/45.12.221.181_tcp.ovpn  

  inflating: ovpn_configs/45.12.221.181_udp.ovpn  

  inflating: ovpn_configs/ee-tll.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ee-tll.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/fi-hel.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/fi-hel.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/fr-par.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/fr-par.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/fr-bod.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/fr-bod.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/185.246.211.69_tcp.ovpn  

  inflating: ovpn_configs/185.246.211.69_udp.ovpn  

  inflating: ovpn_configs/fr-mrs.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/fr-mrs.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ge-tbs.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ge-tbs.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/de-fra.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/de-fra-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/152.89.163.21_tcp.ovpn  

  inflating: ovpn_configs/152.89.163.21_udp.ovpn  

  inflating: ovpn_configs/de-fra-st004.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-st004.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/185.102.219.6_tcp.ovpn  

  inflating: ovpn_configs/185.102.219.6_udp.ovpn  

  inflating: ovpn_configs/de-fra-st003.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-st003.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/de-fra-st005.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-st005.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/de-fra-st002.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-st002.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/de-fra-st001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/de-fra-st001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/gr-ath.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/gr-ath.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/hk-hkg.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/hk-hkg.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/hu-bud.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/hu-bud.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/is-rkv.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/is-rkv.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/in-mum.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/in-mum.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/in-chn.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/in-chn.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/in-idr.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/in-idr.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/id-jak.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/id-jak.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ie-dub.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ie-dub.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/il-tlv.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/il-tlv.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/37.120.201.19_tcp.ovpn  

  inflating: ovpn_configs/37.120.201.19_udp.ovpn  

  inflating: ovpn_configs/185.217.71.21_tcp.ovpn  

  inflating: ovpn_configs/185.217.71.21_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st009.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st009.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st010.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st010.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st012.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st012.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st011.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st011.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st008.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st008.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st013.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st013.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st004.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st004.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/jp-tok-st005.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/jp-tok-st005.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/kz-ura.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/kz-ura.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/lv-rig.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/lv-rig.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/185.153.151.60_tcp.ovpn  

  inflating: ovpn_configs/185.153.151.60_udp.ovpn  

  inflating: ovpn_configs/42.0.30.179_tcp.ovpn  

  inflating: ovpn_configs/42.0.30.179_udp.ovpn  

  inflating: ovpn_configs/mx-mex.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/mx-mex.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/md-chi.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/md-chi.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/nl-ams.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/nl-ams.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/nl-ams-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/nl-ams-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/81.19.208.54_tcp.ovpn  

  inflating: ovpn_configs/81.19.208.54_udp.ovpn  

  inflating: ovpn_configs/180.149.231.67_tcp.ovpn  

  inflating: ovpn_configs/180.149.231.67_udp.ovpn  

  inflating: ovpn_configs/ng-lag.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ng-lag.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/185.225.28.245_tcp.ovpn  

  inflating: ovpn_configs/185.225.28.245_udp.ovpn  

  inflating: ovpn_configs/95.174.66.37_tcp.ovpn  

  inflating: ovpn_configs/95.174.66.37_udp.ovpn  

  inflating: ovpn_configs/pa-pac.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pa-pac.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/pe-lim.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pe-lim.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ph-mnl.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ph-mnl.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/pl-waw.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pl-waw.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/pl-gdn.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pl-gdn.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/pt-lis.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pt-lis.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/5.154.174.67_tcp.ovpn  

  inflating: ovpn_configs/5.154.174.67_udp.ovpn  

  inflating: ovpn_configs/pt-opo.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/pt-opo.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/45.89.175.53_tcp.ovpn  

  inflating: ovpn_configs/45.89.175.53_udp.ovpn  

  inflating: ovpn_configs/ru-mos.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ru-mos.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/152.89.160.213_tcp.ovpn  

  inflating: ovpn_configs/152.89.160.213_udp.ovpn  

  inflating: ovpn_configs/sg-sng-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-in.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-in.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-sng.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-sng-st002.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng-st002.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-sng-st003.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng-st003.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-sng-st001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng-st001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sg-sng-st004.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sg-sng-st004.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/sk-bts.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/sk-bts.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/si-lju.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/si-lju.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/za-jnb.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/za-jnb.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/kr-seo.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/kr-seo.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/82.102.17.179_tcp.ovpn  

  inflating: ovpn_configs/82.102.17.179_udp.ovpn  

  inflating: ovpn_configs/es-bcn.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/es-bcn.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/es-vlc.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/es-vlc.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/se-sto.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/se-sto.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/45.83.91.131_tcp.ovpn  

  inflating: ovpn_configs/45.83.91.131_udp.ovpn  

  inflating: ovpn_configs/84.17.53.86_tcp.ovpn  

  inflating: ovpn_configs/84.17.53.86_udp.ovpn  

  inflating: ovpn_configs/tw-tai.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/tw-tai.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/th-bkk.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/th-bkk.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/tr-ist.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/tr-ist.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ua-iev.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ua-iev.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ae-dub.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ae-dub.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-man.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-man.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon-st001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-st001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-gla.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-gla.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/192.145.126.131_tcp.ovpn  

  inflating: ovpn_configs/192.145.126.131_udp.ovpn  

  inflating: ovpn_configs/5.226.137.10_tcp.ovpn  

  inflating: ovpn_configs/5.226.137.10_udp.ovpn  

  inflating: ovpn_configs/uk-lon-st004.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-st004.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon-st002.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-st002.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon-st003.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-st003.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/uk-lon-st005.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/uk-lon-st005.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-sfo-mp001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-sfo-mp001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-buf.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-buf.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/192.154.253.67_tcp.ovpn  

  inflating: ovpn_configs/192.154.253.67_udp.ovpn  

  inflating: ovpn_configs/193.37.252.197_tcp.ovpn  

  inflating: ovpn_configs/193.37.252.197_udp.ovpn  

  inflating: ovpn_configs/us-sea.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-sea.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/198.147.22.83_tcp.ovpn  

  inflating: ovpn_configs/198.147.22.83_udp.ovpn  

  inflating: ovpn_configs/us-ash.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-ash.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-ltm.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-ltm.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-tpa.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-tpa.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-slc.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-slc.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/104.244.208.211_tcp.ovpn  

  inflating: ovpn_configs/104.244.208.211_udp.ovpn  

  inflating: ovpn_configs/us-nyc.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/66.115.169.35_tcp.ovpn  

  inflating: ovpn_configs/66.115.169.35_udp.ovpn  

  inflating: ovpn_configs/107.181.184.115_tcp.ovpn  

  inflating: ovpn_configs/107.181.184.115_udp.ovpn  

  inflating: ovpn_configs/us-chi.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-chi.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-las.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-las.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-den.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-den.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-dal.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-dal.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-bos.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-bos.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/38.95.110.69_tcp.ovpn  

  inflating: ovpn_configs/38.95.110.69_udp.ovpn  

  inflating: ovpn_configs/us-sfo.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-sfo.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-hou.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-hou.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/148.72.169.209_tcp.ovpn  

  inflating: ovpn_configs/148.72.169.209_udp.ovpn  

  inflating: ovpn_configs/us-bdn.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-bdn.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-st004.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-st004.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-kan.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-kan.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-st005.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-st005.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_udp.ovpn  

  inflating: ovpn_configs/ve-car.prod.surfshark.com_tcp.ovpn  

  inflating: ovpn_configs/ve-car.prod.surfshark.com_udp.ovpn  

Chose: 37.120.201.19_udp.ovpn
`

**Comment by ilteoood** [comment]
So, what is the issue?

The ovpn files are downloaded from surfshark website.

If you need the original one, you should raise a ticket support to them

**Comment by ilmarietto123** [comment]
I don't know, the zip file downloaded browsing the link shown in the website: [https://my.surfshark.com/vpn/api/v1/server/configurations](url) have the correct filenames, the one downloaded from the container has some IP style filenames, as shown in the container log posted. Does the container use the same link?

**Comment by ilteoood** [comment]
Currently is using https://api.surfshark.com/v1/server/configurations.

Let me check your link

**Comment by ilteoood** [comment]
Take a look  at tag 1.1.1, this should be fixed now!

**Comment by ilmarietto123** [comment]
Thanks, it works! =)
