### ISSUE TITLE
Faking a TUN device for NAS users

### ISSUE THREAD

**Issue by BasixKOR** [ilteoood/docker-surfshark#33]
Hi.

First of all, thank you for the amazing image! However as a Synology owner I find it difficult to make Synology pass device to its container, so I checked `docker-transmission-openvpn` which doesn't require passing it.

As it turns out it [creates TUN device on the fly](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L35), allowing users to use it without passing the TUN device.

Could we have similar thing on this image too?

**Comment by ilteoood** [comment]
Hi @BasixKOR,
yes we can do it.

The thing I don't like with that approach is that we are going to create a new device instead of using an existing one.

Did you tried to create your own device with those commands and see if everything is working correctly?

**Comment by BasixKOR** [comment]
Yeah, I agree that this isn't an elegant approach. But in Docker, it seems like the container was able to communicate without any problem with this made-up TUN device.

**Comment by ilteoood** [comment]
Should be available with the tag `latest`.

Please try it and let me know

**Comment by ilteoood** [comment]
Hi @BasixKOR , any news about it?

**Comment by ilteoood** [comment]
Is now available with version 1.3.0
