### ISSUE TITLE
Connected to wrong location.

### ISSUE THREAD

**Issue by jtmaguire** [ilteoood/docker-surfshark#38]
Created container passing;
`      - SURFSHARK_COUNTRY=se
      - SURFSHARK_CITY=sto`
      
Ran curl command to check connection and saw that I had been connected to another country.

`/vpn # curl ipconfig.io/json
{
  "ip": "213.152.165.98",
  "ip_decimal": 3583550818,
  "country": "Netherlands",
  "country_iso": "NL",
  "country_eu": true,
  "latitude": 52.3824,
  "longitude": 4.8995,
  "time_zone": "Europe/Amsterdam",
  "asn": "AS49453",
  "asn_org": "Global Layer B.V.",
  "user_agent": {
    "product": "curl",
    "version": "7.80.0",
    "raw_value": "curl/7.80.0"
  }`
  
 Connected to Stockholm, Sweden server from the mac client and ran the curl command, response stated Sweden.

**Comment by ilteoood** [comment]
In the logs, you should see the final `openvpn` command that has been executed in the startup phase: can you share it?

**Comment by jtmaguire** [comment]
This issue appears to be intermittent - if I experience this again then I will post the command as request.
