### ISSUE TITLE
Access networked containers from LAN

### ISSUE THREAD

**Issue by DeiusShrab** [ilteoood/docker-surfshark#4]
I have been trying to use this container to secure other containers behind a VPN. I have successfully gotten the containers to run with the VPN, but many of them have Web GUIs that are inaccessible while they're using this container for their network.
I have seen other VPN containers that use a NETWORK parameter to pass in your LAN subnet to OpenVPN, is it possible to add something like that to this container?

**Comment by ilteoood** [comment]
Hi,
I don't like that kind of solution, they rely too much on the interfaces naming or current network status.
I suggest you to use a reverse proxy to do this, and configure it as a sidecar: https://containo.us/traefik/ is my favorite!

**Comment by KCS-Mack** [comment]
I see I think this is what I need....
