### ISSUE TITLE
After pull new docker image vpn not works

### ISSUE THREAD

**Issue by Dropsik** [ilteoood/docker-surfshark#40]
tag: latest
docker-compose logs:
```
surfshark    | Chose:
surfshark    | Adding ip route add 192.168.0.0/24 via 172.19.0.1 dev eth0 for attached container web ui access
surfshark    | Do not forget to expose the ports for attached container we ui access
surfshark    | Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.6)
surfshark    | Use --help for more information.
```

**Comment by ilteoood** [comment]
What is the configuration of your container?

**Comment by gvieiraaa** [comment]
I was having the same problem, and just found out what was wrong.

`https://my.surfshark.com/vpn/api/v1/server/configurations` doesn't download all `.ovpn` files available in `https://my.surfshark.com/vpn/manual-setup/main` 

Example: 

Australia lists 5 locations. 

`au-syd.prod.surfshark.com` is one of them.

But the only one present in `ovpn_configs.zip` is `au-mel.prod.surfshark.com`

**Comment by ilteoood** [comment]
You should email surfshark for that, it's not the first time that this happens

**Comment by ilteoood** [comment]
This should have been fixed on Surfshark side.
