### ISSUE TITLE
newbie needs help :(

### ISSUE THREAD

**Issue by BigBlue87** [ilteoood/docker-surfshark#41]
Hi, this is not an issue but more of an I need help. When I copy the command and paste in my information it comes back with the container being unhealthy on my portainer. I run this command through my terminal for Linux

sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name ss -e SURFSHARK_USER=7UtqYdwUEAhQkg8hhqgdb64 -e SURFSHARK_PASSWORD=BFDUswsnXBuvXEbUcFgbT63 ilteoood/docker-surfshark

So then I run this as a stack in portainer, but I am not able to open the command prompt to see what the IP address is for the surfshark container. What is Alpine?

version: "2"

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=7UtqYdwUEAhQkg8hhqgdb64 
            - SURFSHARK_PASSWORD=BFDUswsnXBuvXEbUcFgbT63
            - SURFSHARK_COUNTRY=it
            - SURFSHARK_CITY=mil
            - CONNECTION_TYPE=udp
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always

**Comment by ilteoood** [comment]
Hi,
First of all, you must not insert your username and password here: everyone can use them.

BTW, can you attach the container logs?

**Comment by BigBlue87** [comment]
Hi, Thank you for the quick response. For the username a password I changed it but wanted to show that is the format I was using vs using standard email and password.

Here are the logs you requested. 

**_Transmission:_**
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
sendto: Network unreachable
sendto: Network unreachable
sendto: Network unreachable
sendto: Network unreachable
[2022-04-25 01:11:39.205] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769)
[2022-04-25 01:11:39.205] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243)
[2022-04-25 01:11:39.205] DHT Generating new id (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:389)
[2022-04-25 01:11:39.205] Using settings from "/config" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646)
[2022-04-25 01:11:39.205] Saved "/config/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221)
[2022-04-25 01:11:39.205] Watching "/watch" for new .torrent files (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:698)
[2022-04-25 01:11:41.206] Port Forwarding State changed from "Not forwarded" to "???" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/port-forwarding.c:106)
[2022-04-25 01:12:11.206] DHT Attempting bootstrap from dht.transmissionbt.com (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:299)
[2022-04-25 01:12:16.205] DHT dht.transmissionbt.com:6881: Try again (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:136)
[2022-04-25 01:12:54.206] DHT dht.transmissionbt.com:6881: Try again (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:136)
[2022-04-25 01:13:24.203] DHT dht.transmissionbt.com:6881: Try again (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:136)
[2022-04-25 01:13:58.202] DHT dht.transmissionbt.com:6881: Try again (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:136)

**_Surfshark:_**
  inflating: ovpn_configs/tw-tai.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/tw-tai.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/th-bkk.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/th-bkk.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/tr-ist.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/tr-ist.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/ua-iev.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/ua-iev.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/45.9.250.99_tcp.ovpn  
  inflating: ovpn_configs/45.9.250.99_udp.ovpn  
  inflating: ovpn_configs/uk-man.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-man.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-mp001.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-mp001.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-edi.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-edi.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/193.148.17.83_tcp.ovpn  
  inflating: ovpn_configs/193.148.17.83_udp.ovpn  
  inflating: ovpn_configs/uk-gla.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-gla.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-st004.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-st004.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-st002.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-st002.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-st001.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-st001.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-st003.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-st003.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uk-lon-st005.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uk-lon-st005.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-den.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-den.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-nyc-st001.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-nyc-st002.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-nyc-st003.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-nyc-mp001.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-nyc-mp001.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-sfo-mp001.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-sfo-mp001.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-atl.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-atl.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-sjc.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-sjc.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-tpa.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-tpa.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-buf.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-buf.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-sfo.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-sfo.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-dal.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-dal.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-lax.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-lax.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-dtw.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-dtw.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-sea.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-sea.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/148.72.169.213_tcp.ovpn  
  inflating: ovpn_configs/148.72.169.213_udp.ovpn  
  inflating: ovpn_configs/us-phx.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-phx.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-mia.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-mia.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-slc.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-slc.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-las.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-las.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/154.16.169.7_tcp.ovpn  
  inflating: ovpn_configs/154.16.169.7_udp.ovpn  
  inflating: ovpn_configs/us-nyc.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-nyc.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-kan.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-kan.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-hou.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-hou.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-bdn.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-bdn.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-chi.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-chi.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/198.147.22.147_tcp.ovpn  
  inflating: ovpn_configs/198.147.22.147_udp.ovpn  
  inflating: ovpn_configs/us-bos.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-bos.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-clt.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-clt.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/us-ash.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/us-ash.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/uz-tas.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/uz-tas.prod.surfshark.com_udp.ovpn  
  inflating: ovpn_configs/ve-car.prod.surfshark.com_tcp.ovpn  
  inflating: ovpn_configs/ve-car.prod.surfshark.com_udp.ovpn  
Chose:
Do not forget to expose the ports for attached container we ui access
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.5.6)
Use --help for more information.

The Alpine container would not run but here is the logs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{
  "ip": "9#.2##.#6.##4",
  "hostname": "cpe0#######a617e0-cm0######617de.cpe.net.cable.##.com",
  "city": "Toronto",
  "region": "Ontario",
  "country": "CA",
  "loc": "#####,-7######",
  "org": "AS812 Rogers Communications Canada Inc.",
  "postal": "###",
  "timezone": "America/Toronto",
  "readme": "https://ipinfo.io/missingauth"

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   341  100   341    0     0   1883      0 --:--:-- --:--:-- --:--:--  1883
}

**Comment by ilteoood** [comment]
This seems fixed now, can you confirm?
