### ISSUE TITLE
Stop retrying if my password is incorrect

### ISSUE THREAD

**Issue by gqqnbig** [ilteoood/docker-surfshark#43]
My screen keeps scrolling and I don't know if the server has finished initilizing, until I spot the following lines.

```
surfshark     | 2022-05-13 09:26:00 SENT CONTROL [tw-tai-v018.prod.surfshark.com]: 'PUSH_REQUEST' (status=1)
surfshark     | 2022-05-13 09:26:00 AUTH: Received control message: AUTH_FAILED
surfshark     | 2022-05-13 09:26:00 SIGTERM[soft,auth-failure] received, process exiting
```

Can you stop restarting the container if my password is incorrect?

**Comment by ilteoood** [comment]
You should remove the restart: unless-stopped command

**Comment by gqqnbig** [comment]
I don't know the syntax of [docker-compose.yml](https://github.com/ilteoood/docker-surfshark/blob/master/docker-compose.yml).. but fine, I can look it up.

**Comment by ilteoood** [comment]
Yeah, of course
