### ISSUE TITLE
Use of dockerfile and AUTH_FAILED

### ISSUE THREAD

**Issue by abodilsen** [ilteoood/docker-surfshark#44]
First - thank you for creating this image of all of us :) 

1. I have downloaded the dockerfile and startup.sh.
2. build the image 
3. Tried to run the container 

But I get this error: 
2022-06-02 21:31:45 AUTH: Received control message: AUTH_FAILED
2022-06-02 21:31:45 SIGTERM[soft,auth-failure] received, process exiting

I have tried to enclose the password with specialchars in double qoutes in the dockerfile like below. Is that the way to do it ? 

FROM alpine:latest
LABEL maintainer.name="Matteo Pietro Dazzi" \
    maintainer.email="matteopietro.dazzi@gmail.com" \
    version="1.3.0" \
    description="OpenVPN client configured for SurfShark VPN"
WORKDIR /vpn
ENV SURFSHARK_USER="REPLACED@gmail.com"
ENV SURFSHARK_PASSWORD=">SHITTY5{=PASSWORD[[5cC%nIr;WITH_SPECIAL_CHARS"
ENV SURFSHARK_COUNTRY=
ENV SURFSHARK_CITY=
ENV OPENVPN_OPTS=
ENV CONNECTION_TYPE=tcp
ENV LAN_NETWORK=
ENV CREATE_TUN_DEVICE=
HEALTHCHECK --interval=60s --timeout=10s --start-period=30s CMD curl -L 'https://ipinfo.io'
COPY startup.sh .
RUN apk add --update --no-cache openvpn wget unzip coreutils curl && chmod +x ./startup.sh
ENTRYPOINT [ "./startup.sh" ]

**Comment by ilteoood** [comment]
Why are you trying to build the image?

It is available for everyone on docker hub

**Comment by abodilsen** [comment]
I have build the image locally on my windows 10 with docker desktop. Its when I locally executes a docker run <imagename>

**Comment by ilteoood** [comment]
But you don't have to build the image.
If you use docker run, you can use ilteoood/docker-surfshark as image name and it will be download from docker hub.

**Comment by abodilsen** [comment]
Ok, I will try that. how do you add your password to the contrainer ? As a parameter when you execute the docker run ? And do you encapsulate it in double quotes to hand special characters ?

**Comment by ilteoood** [comment]
Everything is documented here:
https://github.com/ilteoood/docker-surfshark#configuration

**Comment by abodilsen** [comment]
Thank you. But (I am sorry if I missed it ) I cannot find a way to handle special characters in passwords in the documentation :(

**Comment by ilteoood** [comment]
You don't find it here because is related to docker. You should escape special character or use a .env file.

Check the docker run documentation

**Comment by abodilsen** [comment]
The original line 8 from startup.sh did not write my password with special chars correct to the vpn-auth.txt file. 
printf "${SURFSHARK_USER}\n${SURFSHARK_PASSWORD}" > vpn-auth.txt

I replaced with: 
printf '%s' "${SURFSHARK_USER}" > vpn-auth.txt
printf '\n' >> vpn-auth.txt
printf '%s' "${SURFSHARK_PASSWORD}" >> vpn-auth.txt

But I am still getting the AUTH_FAILED error. 
Could you try to build an image with the three new lines and check if you can login fine ?

**Comment by ilteoood** [comment]
All the other users, me included, can login without any trouble.
Does your password includes special chars?
I've tried with `!`, and is still fine.

**Comment by Smiggel** [comment]
> The original line 8 from startup.sh did not write my password with special chars correct to the vpn-auth.txt file. printf "${SURFSHARK_USER}\n${SURFSHARK_PASSWORD}" > vpn-auth.txt
> 
> I replaced with: printf '%s' "${SURFSHARK_USER}" > vpn-auth.txt printf '\n' >> vpn-auth.txt printf '%s' "${SURFSHARK_PASSWORD}" >> vpn-auth.txt
> 
> But I am still getting the AUTH_FAILED error. Could you try to build an image with the three new lines and check if you can login fine ?

Dit you actually copy the right credentials? You should not use your Surfshark username and password. You have to lookup the username en password for the chosen service.
