### ISSUE TITLE
If VPN doesn't connect other containers will use the normal network.

### ISSUE THREAD

**Issue by RemcoSchrijver** [ilteoood/docker-surfshark#48]
I read in previous issues that you say you implemented a kill switch but it seems that this is not the case because transmission exposes my own IP if the surfshark container cannot connect.

**Comment by YabaiKai** [comment]
I notice the same. Recently had this container go unhealthy for ~8 hours, and the containers using this container's network were confirmed to leak through to my host network.

**Comment by sorryusernameisalreadytaken** [comment]
@ilteoood I think this is really important!

Do you have an idea how to fix that?
I think it should be possible with nftables, see here as inspiration:
https://github.com/wfg/docker-openvpn-client/search?q=nftables

**Comment by YabaiKai** [comment]
For what it's worth @sorryusernameisalreadytaken, I have changed to wfg/docker-openvpn-client. Sure, you have to download each (or all) config file for the Surfshark servers you'd like to use, but once you do this initial setup, it is no harder to switch between each of the servers than with this container. Easy one-line change in the config. The assurance of not having a leaky VPN was worth it for me.

**Comment by ilteoood** [comment]
Hi guys, sorry but I'm on holidays rn and previously I've been a little bit busy at work.

Can someone of you paste here the configuration, in order to easily debug it next week?

Thank you so much,
Matteo

**Comment by Smiggel** [comment]
> I read in previous issues that you say you implemented a kill switch but it seems that this is not the case because transmission exposes my own IP if the surfshark container cannot connect.

Noticed the same today during some tests. A kill switch would be nice.

**Comment by ilteoood** [comment]
This has been implemented starting with version 1.5.0.

It is enabled by default.
