### ISSUE TITLE
unable to resolve hosts

### ISSUE THREAD

**Issue by chenks** [ilteoood/docker-surfshark#5]
i installed this on my synology NAS as per the instructions. it appears to be running, but i can't seem to confirm that it has successfully connected.

I connect to it using the Terminal tab. Run the `sh `command to get a new window. Then inside it run, curl ifconfig.me command.
however the response i got was `curl: (6) Could not resolve host: ifconfig.me`

the logs don't appear to be show any connection errors.
how can i check that it actually is connected and working?

![Annotation 2020-07-14 144322](https://user-images.githubusercontent.com/11945919/87432899-8ef52c80-c5e0-11ea-95d9-69c2abd5e2fe.jpg)

```
{
   "cap_add" : [ "NET_ADMIN" ],
   "cap_drop" : null,
   "cmd" : "",
   "cpu_priority" : 50,
   "devices" : [
      {
         "CgroupPermissions" : "rwm",
         "PathInContainer" : "/dev/net/tun",
         "PathOnHost" : "/dev/net/tun"
      }
   ],
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : true,
   "enabled" : true,
   "env_variables" : [
      {
         "key" : "TZ",
         "value" : "Europe/London"
      },
      {
         "key" : "PATH",
         "value" : "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "SURFSHARK_USER",
         "value" : "**************"
      },
      {
         "key" : "SURFSHARK_PASSWORD",
         "value" : "**************"
      },
      {
         "key" : "SURFSHARK_COUNTRY",
         "value" : ""
      },
      {
         "key" : "SURFSHARK_CITY",
         "value" : ""
      },
      {
         "key" : "CONNECTION_TYPE",
         "value" : "tcp"
      }
   ],
   "exporting" : false,
   "id" : "be5a6540ef32b44c2b907711681b60fc1477cde854e69b0229441f898035947a",
   "image" : "ilteoood/docker-surfshark",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "surfshark",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "default",
   "port_bindings" : [],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "use_host_network" : false,
   "volume_bindings" : []
}
```

**Comment by ilteoood** [comment]
Hi,
did you tried to connect to it another container?
Did you tried with the --dns option?

**Comment by chenks** [comment]
no i haven't connected it to another container yet, i was wanting to ensure that it was actually connected and working first before i did that.

at the moment it appears that the vpn container has no internet access.

**Comment by ilteoood** [comment]
Did you tried with the --dns option?

**Comment by chenks** [comment]
dns option on what container? the VPN container or the container i want to use it with?
the documentation is a little vague in regards to DNS option.

also, i would be wanting to use the VPN connection with a container that already exists and is up and running? from what i can see the command appears to want to create a new container to use it with.

**Comment by ilteoood** [comment]
The DNS option is not listed in documentation because you shouldn't need it, I'm trying to help you with some advice.
You could try to use the dns option in the vpn cointainer, but without any detailed log of the vpn container is hard to figure out the problem.

For the running cointaner, you could use the docker CLI to specify the network that should be attached to your running container, btw I suggest you to re-create it (containers should always be re-creatable)

**Comment by chenks** [comment]
i have attached the log if that helps.
all the help is appreciated.

[log.zip](https://github.com/ilteoood/docker-surfshark/files/4919650/log.zip)

**Comment by ilteoood** [comment]
Can you extract them with the docker CLI?
There aren't sufficient.

**Comment by chenks** [comment]
what specifically do you need to see? as that is the log file that docker gave me for that container.
this is docker on a synology NAS.

running `sudo docker logs <container_name>` gives the same result as the CSV file i posted

**Comment by ilteoood** [comment]
Ok, can you try to:
- delete this container
- set a country in the environment variable (it, for example)
- recreate the container
- attach new logs

**Comment by chenks** [comment]
trying this now, however when i use the command

`sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --name surfshark -e SURFSHARK_COUNTRY=it SURFSHARK_USER=7q5dYeoq2cg5gCrPdy3o9get -e SURFSHARK_PASSWORD=NRD4kvjL2HwJFnEkAtSwdy7J ilteoood/docker-surfshark`

it comes back with 

`docker: invalid reference format: repository name must be lowercase.`

remove the SURFSHARK_COUNTRY option and it gives no error

**Comment by ilteoood** [comment]
@chenks 
I've removed your comment, because in the history everyone can see your credentials.
The error "docker: invalid reference format: repository name must be lowercase." appear because you missed the "-e" parameter between SURFSHARK_COUNTRY and SURFSHAR_USER.

Please, retry with the correct syntax.

**Comment by chenks** [comment]
OK i have re-created with the country set, and still same error

```
/vpn # curl ifconfig.me                                                                                                   
curl: (6) Could not resolve host: ifconfig.me
```

**Comment by ilteoood** [comment]
OK, just a few question: which is your os? Are you sure that you have the /dev/net/tun device?

I've retried everything, but without any error
![image](https://user-images.githubusercontent.com/6383527/87571280-17033100-c6ca-11ea-9746-d145e41dd8ae.png)

![image](https://user-images.githubusercontent.com/6383527/87571295-1ec2d580-c6ca-11ea-8da7-932c6a9d2ecb.png)

**Comment by chenks** [comment]
it's a Synology NAS, so it's a very heavily customized Debian fork that uses Upstart (vs. sysvinit or systemd).
how would i check if i have the  /dev/net/tun device?

this is my log showing the same as yours

```
Wed Jul 15 12:25:49 2020 TUN/TAP device tun0 opened
Wed Jul 15 12:25:49 2020 TUN/TAP TX queue length set to 100
Wed Jul 15 12:25:49 2020 /sbin/ip link set dev tun0 up mtu 1500
Wed Jul 15 12:25:49 2020 /sbin/ip addr add dev tun0 10.7.7.10/24 broadcast 10.7.7.255
Wed Jul 15 12:25:49 2020 /sbin/ip route add 212.102.54.177/32 via 172.17.0.1
Wed Jul 15 12:25:49 2020 /sbin/ip route add 0.0.0.0/1 via 10.7.7.1
Wed Jul 15 12:25:49 2020 /sbin/ip route add 128.0.0.0/1 via 10.7.7.1
Wed Jul 15 12:25:49 2020 Initialization Sequence Completed
```

**Comment by ilteoood** [comment]
You can check with a simple cd to that path, using root permissions

Il giorno gio 16 lug 2020 alle ore 12:26 chenks <notifications@github.com>
ha scritto:

**Comment by chenks** [comment]
within /dev/net i have a file called "tun".

![Annotation 2020-07-16 114905](https://user-images.githubusercontent.com/11945919/87662661-70b33c00-c75a-11ea-989a-3f5085ccfd0d.jpg)

**Comment by ilteoood** [comment]
This is not an issue related to the image, but related to your system.
Please, consider to predispose your system for the OpenVPN container, as described here: https://www.reddit.com/r/synology/comments/74te0y/howto_deploy_openvpn_on_synology_using_docker/

**Comment by chenks** [comment]
so it's not a DNS issue then?
the link you posted appears to be about deploying an OpenVPN server?

**Comment by ilteoood** [comment]
Nope. The container is initially connected to the VPN (as you can see with the message Wed Jul 15 12:25:49 2020 Initialization Sequence Completed), but after the connection can't reach internet because the dedicated device (tun) isn't properly configured.

**Comment by chenks** [comment]
having looked into this further, i believe the tun is configured correctly, as the VPN container has interent access if you use just IP addresses, it only doesn't work when usign FQDN, therefore it appears to be a DNS issues.

can you provide an example of creating the container with DNS option?

**Comment by ilteoood** [comment]
Just add the --dns options on container creation, as documented here:
https://web.cbmain.cbdom.it/jira/browse/CM-11357?jql=text%20~%20%22business%22

**Comment by chenks** [comment]
URL isn't valid

**Comment by ilteoood** [comment]
Just add --dns option on container creation, as documented here:
https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by chenks** [comment]
just an FYI, adding the DNS option did indeed make it work. it now resolves FQDN correctly.

`sudo docker run -it --cap-add=NET_ADMIN --device /dev/net/tun --dns=8.8.8.8 --name surfshark -e SURFSHARK_USER=************** -e SURFSHARK_COUNTRY=nl -e SURFSHARK_PASSWORD=************** ilteoood/docker-surfshark`
