### ISSUE TITLE
"alpine" container offline, stops whole stack from working.

### ISSUE THREAD

**Issue by derrick087** [ilteoood/docker-surfshark#50]
The container "alpine" in my Portainer stack randomly goes offline causing the whole stack to stop working. Is there a way to prevent this from happening or at least have it auto restart the whole stack?

So far as a workaround, I've been manually stopping the entire stack and starting it up again from Portainer whenever I catch it offline. Resetting just the "alpine" container doesn't work. I must stop the entire stack and reenable it.

I'm open to any suggestions I'm still new to working with Docker. I've attached a copy of my Portainer stack minus the personal info. [my stack copy.txt](https://github.com/ilteoood/docker-surfshark/files/9278655/my.stack.copy.txt)

Thank you.

**Comment by ilteoood** [comment]
The alpine container is there just to test that the ip is changing, you can remove it from your stack.

**Comment by derrick087** [comment]
> The alpine container is there just to test that the ip is changing, you can remove it from your stack.

Oh, I see! Thank you for the quick reply.
