### ISSUE TITLE
Webinterface not available

### ISSUE THREAD

**Issue by Smiggel** [ilteoood/docker-surfshark#51]
I tried your stack today. I see Surfshark connects properly. Alpine is running and has the ip of surfshark. So does transmission.

However, the interface of Transmission is not available. Even in the example the port is set, it does not seem to work. Has something changed in the Transmission docker? Of is there an issue with the Surfshark docker?

**Comment by Smiggel** [comment]
Tried a different docker container with the port added to Surfshark container. IP is form Surfshark, but interface is not available again.

**Comment by ilteoood** [comment]
How are you trying to access it, using the surfshark IP or using a local IP?

**Comment by Smiggel** [comment]
> How are you trying to access it, using the surfshark IP or using a local IP?

I use the local IP of my NAS.

**Comment by Smiggel** [comment]
Tried it with the NordVPN container: ghcr.io/bubuntux/nordlynx

The same transmission container web interface is available then. When I connect it to SurfShark, the webinterface is unavailable. So it seems it has to do with the port forwarding of the container.

**Comment by Smiggel** [comment]
Finally found the problem after trying many different setups. "LAN_NETWORK" can not be empty. I actually need to set my subnet to make it work. Without it, the interfaces are not accessible.
