### ISSUE TITLE
what is wrong

### ISSUE THREAD

**Issue by xzakier** [ilteoood/docker-surfshark#56]
version: "3.3"
services: 
 surfshark:
  image: ilteoood/docker-surfshark
  container_name: surfshark
  environment: 
   - SURFSHARK_USER=xxxx
   - SURFSHARK_PASSWORD=xxxx
   - SURFSHARK_COUNTRY=nl
   - SURFSHARK_CITY=ams
   - CONNECTION_TYPE=udp
   - LAN_NETWORK=
  cap_add: 
   - NET_ADMIN
  devices:
   - /dev/net/tun
  ports:
   - 8080:8080
  restart: unless-stopped
  dns:
   - 1.1.1.1
 qbittorrent:
  image: lscr.io/linuxserver/qbittorrent:latest
  container_name: qbittorrent
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=Etc/UTC
   - WEBUI_PORT=8080
  volumes:
   - /root/qbittorrent/config:/config
   - /root/vv/jellyfin/SEED:/downloads
  ports:
   - 8080:8080
   - 6881:6881
   - 6881:6881/udp
  restart: unless-stopped

**Comment by ilteoood** [comment]
What error are you facing?

**Comment by xzakier** [comment]
Everything gets deployed, but I can't access on port 8080

**Comment by ilteoood** [comment]
LAN_NETWORK parameter is missing.
