### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by NeuronButter** [ilteoood/docker-surfshark#7]
Hey there,
Just a quick question. Does the container force the connection via OpenVPN, and terminate connections if the VPN doesn't connect, or does it fallback to your regular internet?

**Comment by ilteoood** [comment]
If the VPN doesn't connect, I suppose that openvpn process will be closed, and the container killed.
With docker-surfshark you are using openvpn to route the traffic: if it dies, the connection is broken.
