### ISSUE TITLE
Resolving my.surfshark.com (my.surfshark.com)... failed: Try again. In Kubernetes

### ISSUE THREAD

**Issue by mariogruizdiaz** [ilteoood/docker-surfshark#70]
Is it possible to run it in Kubernetes?

Logs:

--2023-06-09 15:04:02--  https://my.surfshark.com/vpn/api/v1/server/configurations
Resolving my.surfshark.com (my.surfshark.com)... failed: Try again.
wget: unable to resolve host address 'my.surfshark.com'
Archive:  ovpn_configs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ovpn_configs.zip or
        ovpn_configs.zip.zip, and cannot find ovpn_configs.zip.ZIP, period.
./startup.sh: cd: line 8: can't cd to ovpn_configs: No such file or directory
ls: cannot access 'AR*': No such file or directory
Chose:
Do not forget to expose the ports for attached container web ui access
Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: config (2.6.4)
Use --help for more information.
Resetting all rules to installed defaults. Proceed with operation (y|n)? Aborted
Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
Default outgoing policy changed to 'deny'
(be sure to update your rules accordingly)
Rules updated
Rules updated (v6)
Firewall is active and enabled on system startup

**Comment by ilteoood** [comment]
Never tried it with k8s, and I don't even have an instance to test it 🤔

I think that you should check your network policies

**Comment by leonardofaria** [comment]
Was looking at `startup.sh` file and the filenames from surfshark no longer match what is on the script. Instead of `SURFSHARK_COUNTRY=AR` try `SURFSHARK_COUNTRY=rhk_ar`

**Comment by ilteoood** [comment]
@leonardofaria that's a different issue that has been already fixed with a new version release
