### ISSUE TITLE
Set CREATE_TUN_DEVICE to true but got an error

### ISSUE THREAD

**Issue by BobWs** [ilteoood/docker-surfshark#75]
Hi,
I've set the env. `CREATE_TUN_DEVICE: true` but still got an error message that `/dev/net/tun` could not be created on docker on my Synology NAS. I had to manual enable this for it to work. Did I do something wrong?

**Comment by ilteoood** [comment]
Synology could behave differently than normal Linux systems, unfortunately I don't own one of them to try it by myself. Is it working now? If so, would you like to contribute to enhance the readme?

**Comment by BobWs** [comment]
> Synology could behave differently than normal Linux systems, unfortunately I don't own one of them to try it by myself. Is it working now? If so, would you like to contribute to enhance the readme? 

Yes it is working for now! Of course I would love to contribute to help others. 
What I did to get this to work on my Synology NAS is to first add a OpenVPN connection on the NAS this can be found in DSM / Network / create VPN and then choose OpenVPN to create a new VPN connection. After doing this the /net/dev/tun is created and the surfshark container is working.
