### ISSUE TITLE
ERROR 403: Forbidden

### ISSUE THREAD

**Issue by Krylanc3lo** [ilteoood/docker-surfshark#81]
hello,

I hope you are doing well.

I am getting the below error message since tonight, any idea what might be happening?

--2023-10-27 02:23:14--  https://my.surfshark.com/vpn/api/v1/server/configurations
Resolving my.surfshark.com (my.surfshark.com)... 172.64.150.210, 104.18.37.46, 2606:4700:4400::6812:252e, ...
Connecting to my.surfshark.com (my.surfshark.com)|172.64.150.210|:443... connected.
HTTP request sent, awaiting response... Archive:  ovpn_configs.zip
403 Forbidden
2023-10-27 02:23:14 ERROR 403: Forbidden.

Thanks a lot

**Comment by millsjoe** [comment]
looks like there's some blocking on `wget` at the moment for unknown reasons. `curl` still looks to be working or they have an alternative url ( https://my.shark-china.com/vpn/api/v1/server/configurations ) which still works with `wget`. I'll raise a PR

**Comment by millsjoe** [comment]
raised the issue with surfshark and they fixed it instead. want to try again @Krylanc3lo?
