### ISSUE TITLE
Unable to connect to Socks5

### ISSUE THREAD

**Issue by bsudhir6** [ilteoood/docker-surfshark#84]
Hello I have created docker containers  they are running fine including ipinfo container. But when I tried to use container as socks5 proxy in an app its not working. curl command I tried\

C:\Users\XXXXXXXX>curl --socks5 localhost:1080 https://www.facebook.com
curl: (97) Can't complete SOCKS5 connection to www.facebook.com. (8)

can you tell me how to use this container as proxy server.

**Comment by ilteoood** [comment]
I need more info, like how you are creating the container
