### ISSUE TITLE
Is it possible to use both socks5 and http / https proxies ?

### ISSUE THREAD

**Issue by Krylanc3lo** [ilteoood/docker-surfshark#88]
Hello,

I hope you are doing well. I am trying to activate the proxy on http or https, on top of socks5. do you know how I could do it ?

Thanks a lot for your help

**Comment by ilteoood** [comment]
It's possible, but not on top of the socks proxy. Atm you should use a sidecar container

**Comment by Krylanc3lo** [comment]
OK, thanks a lot. I will investigate then

**Comment by ilteoood** [comment]
If you want to implement it in this container, feel free to open a PR
