### ISSUE TITLE
No Connection with Version 1.8.1

### ISSUE THREAD

**Issue by Tobsche1** [ilteoood/docker-surfshark#94]
I use Surfshark with Firefox. I use an Docker-compose.yml file. With version 1.80 works all very well.
With the new Version 1.81 works nothing. Firefox is not reachable. I send 2 Pictures in this post. 1. The Yml and 2. the logs from Surfshark.

Maybe you can help me ? 

greetings 

Tobsche1
![surfshark yml](https://github.com/ilteoood/docker-surfshark/assets/172377810/d9193026-bdd3-46af-a08b-b0f02f9ffaf1)
![surfshark1 8 1](https://github.com/ilteoood/docker-surfshark/assets/172377810/f0296639-b9d6-438b-94b7-f9a9478cd7cb)

**Comment by Dropsik** [comment]
Same problem:
```
surfshark            | Adding ip route add 192.168.0.0/24 via 172.18.0.1 dev eth0 for attached container web ui access
surfshark            | Do not forget to expose the ports for attached container web ui access
surfshark            | Options error: Unrecognized option or missing or extra parameter(s) in [CMD-LINE]:1: mute-replay-warnings (2.6.10)
surfshark            | Use --help for more information.
surfshark            | Resetting all rules to installed defaults. Proceed with operation (y|n)? Aborted
surfshark            | Default incoming policy changed to 'deny'
surfshark            | (be sure to update your rules accordingly)
surfshark            | Default outgoing policy changed to 'deny'
surfshark            | (be sure to update your rules accordingly)
surfshark            | Skipping adding existing rule
surfshark            | Skipping adding existing rule (v6)
surfshark            | Firewall is active and enabled on system startup
```

**Comment by ilteoood** [comment]
I've just re-published version 1.8.1. Can you re-pull it and test it?

**Comment by Dropsik** [comment]
Confirmed, works!

**Comment by Tobsche1** [comment]
it works, thanks for your fast support !!
