### ISSUE TITLE
Problem Install on Synology

### ISSUE THREAD

**Issue by jean75000** [ilteoood/docker-surfshark#97]
Hello I am trying to install on my synology but I can't do it can you help me? 
![image](https://github.com/user-attachments/assets/e8bfb44e-b482-488c-91ba-33037a364583)
surfshark container stops with errors after a few seconds:
![image](https://github.com/user-attachments/assets/6b955c9c-2a42-4631-9734-be578b78dab7)

Thanks

**Comment by ilteoood** [comment]
I think it could be similar to: https://github.com/ilteoood/docker-surfshark/issues/92

**Comment by jean75000** [comment]
Thanks, I went with the gluetun solution and it works
